//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorityClient.RoleSer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoleSer.IRoleService")]
    public interface IRoleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetAllList", ReplyAction="http://tempuri.org/IRoleService/GetAllListResponse")]
        System.Data.DataTable GetAllList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetAllEnableList", ReplyAction="http://tempuri.org/IRoleService/GetAllEnableListResponse")]
        System.Data.DataTable GetAllEnableList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/Save", ReplyAction="http://tempuri.org/IRoleService/SaveResponse")]
        int Save(AuthorityEntity.Role p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/Delete", ReplyAction="http://tempuri.org/IRoleService/DeleteResponse")]
        int Delete(string id, ref string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/Exit", ReplyAction="http://tempuri.org/IRoleService/ExitResponse")]
        bool Exit(string id, string code, string name, ref string errorMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetRoleClass", ReplyAction="http://tempuri.org/IRoleService/GetRoleClassResponse")]
        string[] GetRoleClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetUserList", ReplyAction="http://tempuri.org/IRoleService/GetUserListResponse")]
        System.Data.DataTable GetUserList(string[] roleIDs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoleServiceChannel : AuthorityClient.RoleSer.IRoleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoleServiceClient : System.ServiceModel.ClientBase<AuthorityClient.RoleSer.IRoleService>, AuthorityClient.RoleSer.IRoleService {
        
        public RoleServiceClient() {
        }
        
        public RoleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllList() {
            return base.Channel.GetAllList();
        }
        
        public System.Data.DataTable GetAllEnableList() {
            return base.Channel.GetAllEnableList();
        }
        
        public int Save(AuthorityEntity.Role p) {
            return base.Channel.Save(p);
        }
        
        public int Delete(string id, ref string error) {
            return base.Channel.Delete(id, ref error);
        }
        
        public bool Exit(string id, string code, string name, ref string errorMsg) {
            return base.Channel.Exit(id, code, name, ref errorMsg);
        }
        
        public string[] GetRoleClass() {
            return base.Channel.GetRoleClass();
        }
        
        public System.Data.DataTable GetUserList(string[] roleIDs) {
            return base.Channel.GetUserList(roleIDs);
        }
    }
}
