//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorityClient.OrgPositionsSer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrgPositionsSer.IOrgPositionsService")]
    public interface IOrgPositionsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrgPositionsService/GetAllList", ReplyAction="http://tempuri.org/IOrgPositionsService/GetAllListResponse")]
        System.Data.DataTable GetAllList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrgPositionsService/Save", ReplyAction="http://tempuri.org/IOrgPositionsService/SaveResponse")]
        int Save(AuthorityEntity.OrgPositions p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrgPositionsService/Delete", ReplyAction="http://tempuri.org/IOrgPositionsService/DeleteResponse")]
        int Delete(string id, ref string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrgPositionsService/Exit", ReplyAction="http://tempuri.org/IOrgPositionsService/ExitResponse")]
        bool Exit(string id, string code, string name, ref string errorMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrgPositionsServiceChannel : AuthorityClient.OrgPositionsSer.IOrgPositionsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrgPositionsServiceClient : System.ServiceModel.ClientBase<AuthorityClient.OrgPositionsSer.IOrgPositionsService>, AuthorityClient.OrgPositionsSer.IOrgPositionsService {
        
        public OrgPositionsServiceClient() {
        }
        
        public OrgPositionsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrgPositionsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrgPositionsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrgPositionsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllList() {
            return base.Channel.GetAllList();
        }
        
        public int Save(AuthorityEntity.OrgPositions p) {
            return base.Channel.Save(p);
        }
        
        public int Delete(string id, ref string error) {
            return base.Channel.Delete(id, ref error);
        }
        
        public bool Exit(string id, string code, string name, ref string errorMsg) {
            return base.Channel.Exit(id, code, name, ref errorMsg);
        }
    }
}
