//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorityClient.MenuInfoSer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenuInfoSer.IMenuInfoService")]
    public interface IMenuInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuInfoService/GetAllList", ReplyAction="http://tempuri.org/IMenuInfoService/GetAllListResponse")]
        System.Data.DataTable GetAllList(string funcid, string parentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuInfoService/GetMenuListByFuncID", ReplyAction="http://tempuri.org/IMenuInfoService/GetMenuListByFuncIDResponse")]
        System.Data.DataTable GetMenuListByFuncID(string funcid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuInfoService/SaveList", ReplyAction="http://tempuri.org/IMenuInfoService/SaveListResponse")]
        int SaveList(AuthorityEntity.MenuInfo[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuInfoService/Delete", ReplyAction="http://tempuri.org/IMenuInfoService/DeleteResponse")]
        int Delete(string classcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuInfoService/Exit", ReplyAction="http://tempuri.org/IMenuInfoService/ExitResponse")]
        bool Exit(string parentID, string id, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuInfoService/GetMenuListByRole", ReplyAction="http://tempuri.org/IMenuInfoService/GetMenuListByRoleResponse")]
        System.Data.DataTable GetMenuListByRole(string funcID, string[] roleid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuInfoService/GetMenu", ReplyAction="http://tempuri.org/IMenuInfoService/GetMenuResponse")]
        AuthorityEntity.MenuInfo GetMenu(string menuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuInfoService/GetRootMenu", ReplyAction="http://tempuri.org/IMenuInfoService/GetRootMenuResponse")]
        System.Data.DataTable GetRootMenu(string fucnID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenuInfoServiceChannel : AuthorityClient.MenuInfoSer.IMenuInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuInfoServiceClient : System.ServiceModel.ClientBase<AuthorityClient.MenuInfoSer.IMenuInfoService>, AuthorityClient.MenuInfoSer.IMenuInfoService {
        
        public MenuInfoServiceClient() {
        }
        
        public MenuInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenuInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllList(string funcid, string parentid) {
            return base.Channel.GetAllList(funcid, parentid);
        }
        
        public System.Data.DataTable GetMenuListByFuncID(string funcid) {
            return base.Channel.GetMenuListByFuncID(funcid);
        }
        
        public int SaveList(AuthorityEntity.MenuInfo[] list) {
            return base.Channel.SaveList(list);
        }
        
        public int Delete(string classcode) {
            return base.Channel.Delete(classcode);
        }
        
        public bool Exit(string parentID, string id, string code) {
            return base.Channel.Exit(parentID, id, code);
        }
        
        public System.Data.DataTable GetMenuListByRole(string funcID, string[] roleid) {
            return base.Channel.GetMenuListByRole(funcID, roleid);
        }
        
        public AuthorityEntity.MenuInfo GetMenu(string menuID) {
            return base.Channel.GetMenu(menuID);
        }
        
        public System.Data.DataTable GetRootMenu(string fucnID) {
            return base.Channel.GetRootMenu(fucnID);
        }
    }
}
