//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorityClient.FunctionInfoSer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FunctionInfoSer.IFunctionInfoService")]
    public interface IFunctionInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/GetAllList", ReplyAction="http://tempuri.org/IFunctionInfoService/GetAllListResponse")]
        System.Data.DataTable GetAllList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/Save", ReplyAction="http://tempuri.org/IFunctionInfoService/SaveResponse")]
        int Save(AuthorityEntity.FunctionInfo item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/SaveList", ReplyAction="http://tempuri.org/IFunctionInfoService/SaveListResponse")]
        int SaveList(AuthorityEntity.FunctionInfo[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/Delete", ReplyAction="http://tempuri.org/IFunctionInfoService/DeleteResponse")]
        int Delete(string classcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/Exit", ReplyAction="http://tempuri.org/IFunctionInfoService/ExitResponse")]
        bool Exit(string id, string parentID, string code, string name, ref string errorMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/GetGroupClass", ReplyAction="http://tempuri.org/IFunctionInfoService/GetGroupClassResponse")]
        string[] GetGroupClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/FindDefaultMenu", ReplyAction="http://tempuri.org/IFunctionInfoService/FindDefaultMenuResponse")]
        System.Data.DataTable FindDefaultMenu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/GetEntityByName", ReplyAction="http://tempuri.org/IFunctionInfoService/GetEntityByNameResponse")]
        AuthorityEntity.FunctionInfo GetEntityByName(string code, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/GetEntity", ReplyAction="http://tempuri.org/IFunctionInfoService/GetEntityResponse")]
        AuthorityEntity.FunctionInfo GetEntity(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/GetCanSetPermissionFunc", ReplyAction="http://tempuri.org/IFunctionInfoService/GetCanSetPermissionFuncResponse")]
        System.Data.DataTable GetCanSetPermissionFunc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/GetCanSetPermissionMenu", ReplyAction="http://tempuri.org/IFunctionInfoService/GetCanSetPermissionMenuResponse")]
        System.Data.DataTable GetCanSetPermissionMenu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/GetPermission", ReplyAction="http://tempuri.org/IFunctionInfoService/GetPermissionResponse")]
        System.Data.DataTable GetPermission();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/SavePermission", ReplyAction="http://tempuri.org/IFunctionInfoService/SavePermissionResponse")]
        int SavePermission(AuthorityEntity.Permission[] AuthorityList, ref int version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionInfoService/GetAllFunctByRole", ReplyAction="http://tempuri.org/IFunctionInfoService/GetAllFunctByRoleResponse")]
        System.Data.DataTable GetAllFunctByRole(string[] roleids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFunctionInfoServiceChannel : AuthorityClient.FunctionInfoSer.IFunctionInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FunctionInfoServiceClient : System.ServiceModel.ClientBase<AuthorityClient.FunctionInfoSer.IFunctionInfoService>, AuthorityClient.FunctionInfoSer.IFunctionInfoService {
        
        public FunctionInfoServiceClient() {
        }
        
        public FunctionInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FunctionInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FunctionInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FunctionInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllList() {
            return base.Channel.GetAllList();
        }
        
        public int Save(AuthorityEntity.FunctionInfo item) {
            return base.Channel.Save(item);
        }
        
        public int SaveList(AuthorityEntity.FunctionInfo[] list) {
            return base.Channel.SaveList(list);
        }
        
        public int Delete(string classcode) {
            return base.Channel.Delete(classcode);
        }
        
        public bool Exit(string id, string parentID, string code, string name, ref string errorMsg) {
            return base.Channel.Exit(id, parentID, code, name, ref errorMsg);
        }
        
        public string[] GetGroupClass() {
            return base.Channel.GetGroupClass();
        }
        
        public System.Data.DataTable FindDefaultMenu() {
            return base.Channel.FindDefaultMenu();
        }
        
        public AuthorityEntity.FunctionInfo GetEntityByName(string code, string name) {
            return base.Channel.GetEntityByName(code, name);
        }
        
        public AuthorityEntity.FunctionInfo GetEntity(string id) {
            return base.Channel.GetEntity(id);
        }
        
        public System.Data.DataTable GetCanSetPermissionFunc() {
            return base.Channel.GetCanSetPermissionFunc();
        }
        
        public System.Data.DataTable GetCanSetPermissionMenu() {
            return base.Channel.GetCanSetPermissionMenu();
        }
        
        public System.Data.DataTable GetPermission() {
            return base.Channel.GetPermission();
        }
        
        public int SavePermission(AuthorityEntity.Permission[] AuthorityList, ref int version) {
            return base.Channel.SavePermission(AuthorityList, ref version);
        }
        
        public System.Data.DataTable GetAllFunctByRole(string[] roleids) {
            return base.Channel.GetAllFunctByRole(roleids);
        }
    }
}
