//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorityClient.OrganizationInfoSer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrganizationInfoSer.IOrganizationInfoService")]
    public interface IOrganizationInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/GetAllList", ReplyAction="http://tempuri.org/IOrganizationInfoService/GetAllListResponse")]
        System.Data.DataTable GetAllList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/GetDataTableWithSelect", ReplyAction="http://tempuri.org/IOrganizationInfoService/GetDataTableWithSelectResponse")]
        System.Data.DataTable GetDataTableWithSelect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/GetDataTableWithSelectTree", ReplyAction="http://tempuri.org/IOrganizationInfoService/GetDataTableWithSelectTreeResponse")]
        System.Data.DataTable GetDataTableWithSelectTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/Save", ReplyAction="http://tempuri.org/IOrganizationInfoService/SaveResponse")]
        int Save(AuthorityEntity.OrganizationInfo p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/Delete", ReplyAction="http://tempuri.org/IOrganizationInfoService/DeleteResponse")]
        int Delete(string classcode, ref string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/Exit", ReplyAction="http://tempuri.org/IOrganizationInfoService/ExitResponse")]
        bool Exit(string id, string parentID, string code, string name, ref string errorMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/GetFzr", ReplyAction="http://tempuri.org/IOrganizationInfoService/GetFzrResponse")]
        AuthorityEntity.UserInfo GetFzr(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/GetSjBmFzr", ReplyAction="http://tempuri.org/IOrganizationInfoService/GetSjBmFzrResponse")]
        AuthorityEntity.UserInfo GetSjBmFzr(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/GetUserList", ReplyAction="http://tempuri.org/IOrganizationInfoService/GetUserListResponse")]
        System.Data.DataTable GetUserList(string[] departIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/GetUserListByUserIds", ReplyAction="http://tempuri.org/IOrganizationInfoService/GetUserListByUserIdsResponse")]
        System.Data.DataTable GetUserListByUserIds(string[] userIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/GetOrgnizationByUserID", ReplyAction="http://tempuri.org/IOrganizationInfoService/GetOrgnizationByUserIDResponse")]
        System.Data.DataTable GetOrgnizationByUserID(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/SaveOrgList", ReplyAction="http://tempuri.org/IOrganizationInfoService/SaveOrgListResponse")]
        int SaveOrgList(AuthorityEntity.OrgUserRalation[] orgList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/RemoveUser", ReplyAction="http://tempuri.org/IOrganizationInfoService/RemoveUserResponse")]
        int RemoveUser(string departID, string[] userids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationInfoService/GetUserInfo", ReplyAction="http://tempuri.org/IOrganizationInfoService/GetUserInfoResponse")]
        AuthorityEntity.UserInfo GetUserInfo(string UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrganizationInfoServiceChannel : AuthorityClient.OrganizationInfoSer.IOrganizationInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrganizationInfoServiceClient : System.ServiceModel.ClientBase<AuthorityClient.OrganizationInfoSer.IOrganizationInfoService>, AuthorityClient.OrganizationInfoSer.IOrganizationInfoService {
        
        public OrganizationInfoServiceClient() {
        }
        
        public OrganizationInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrganizationInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllList() {
            return base.Channel.GetAllList();
        }
        
        public System.Data.DataTable GetDataTableWithSelect() {
            return base.Channel.GetDataTableWithSelect();
        }
        
        public System.Data.DataTable GetDataTableWithSelectTree() {
            return base.Channel.GetDataTableWithSelectTree();
        }
        
        public int Save(AuthorityEntity.OrganizationInfo p) {
            return base.Channel.Save(p);
        }
        
        public int Delete(string classcode, ref string error) {
            return base.Channel.Delete(classcode, ref error);
        }
        
        public bool Exit(string id, string parentID, string code, string name, ref string errorMsg) {
            return base.Channel.Exit(id, parentID, code, name, ref errorMsg);
        }
        
        public AuthorityEntity.UserInfo GetFzr(string UserID) {
            return base.Channel.GetFzr(UserID);
        }
        
        public AuthorityEntity.UserInfo GetSjBmFzr(string UserID) {
            return base.Channel.GetSjBmFzr(UserID);
        }
        
        public System.Data.DataTable GetUserList(string[] departIDs) {
            return base.Channel.GetUserList(departIDs);
        }
        
        public System.Data.DataTable GetUserListByUserIds(string[] userIDs) {
            return base.Channel.GetUserListByUserIds(userIDs);
        }
        
        public System.Data.DataTable GetOrgnizationByUserID(string userID) {
            return base.Channel.GetOrgnizationByUserID(userID);
        }
        
        public int SaveOrgList(AuthorityEntity.OrgUserRalation[] orgList) {
            return base.Channel.SaveOrgList(orgList);
        }
        
        public int RemoveUser(string departID, string[] userids) {
            return base.Channel.RemoveUser(departID, userids);
        }
        
        public AuthorityEntity.UserInfo GetUserInfo(string UserID) {
            return base.Channel.GetUserInfo(UserID);
        }
    }
}
