//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorityClient.LoginSer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginSer.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Login", ReplyAction="http://tempuri.org/ILoginService/LoginResponse")]
        AuthorityEntity.UserInfo Login(string appcode, string userno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetRoleInfo", ReplyAction="http://tempuri.org/ILoginService/GetRoleInfoResponse")]
        System.Data.DataTable GetRoleInfo(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/Save", ReplyAction="http://tempuri.org/ILoginService/SaveResponse")]
        int Save(AuthorityEntity.SystemSessionLog log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetDateTime", ReplyAction="http://tempuri.org/ILoginService/GetDateTimeResponse")]
        System.DateTime GetDateTime();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : AuthorityClient.LoginSer.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<AuthorityClient.LoginSer.ILoginService>, AuthorityClient.LoginSer.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AuthorityEntity.UserInfo Login(string appcode, string userno) {
            return base.Channel.Login(appcode, userno);
        }
        
        public System.Data.DataTable GetRoleInfo(string userID) {
            return base.Channel.GetRoleInfo(userID);
        }
        
        public int Save(AuthorityEntity.SystemSessionLog log) {
            return base.Channel.Save(log);
        }
        
        public System.DateTime GetDateTime() {
            return base.Channel.GetDateTime();
        }
    }
}
